version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: unload.sh
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      runas: ubuntu
      
    

