version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Zipping Files
          command: |
            pwd
            ls -al
            zip -r DjangoApp1.zip DjangoApp1/
            echo "Zip Done"
            sudo chmod 775 DjangoApp1.zip
            ls -al
      - aws-s3/copy:
          from: DjangoApp1.zip
          to: s3://codedeploy-kmvanesa-me
workflows:
  deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          application-name: csye6225-webapp
          bundle-bucket: codedeploy-kmvanesa-me
          bundle-key: DjangoApp1
          deployment-config: CodeDeployDefault.OneAtATime
          deployment-group: csye6225-webapp-deployment
          service-role-arn: arn:aws:iam::708581696554:roleCodeDeployServiceRole