# Generated by Django 3.0.3 on 2020-06-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200615_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
    ]
