# Generated by Django 3.0.3 on 2020-06-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200615_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures/')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
