# Generated by Django 3.0.3 on 2020-06-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
    ]
