# Generated by Django 3.0.3 on 2020-06-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200602_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
