# Generated by Django 3.0.3 on 2020-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200603_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Image URL'),
        ),
    ]
